// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjCpuZVpiJNDUPld_HBhFKdaOIjALJdfY',
    appId: '1:288296090804:web:a34e7b73473182bea62be1',
    messagingSenderId: '288296090804',
    projectId: 'yoo-yoo-bfe2e',
    authDomain: 'yoo-yoo-bfe2e.firebaseapp.com',
    storageBucket: 'yoo-yoo-bfe2e.appspot.com',
    measurementId: 'G-3XB3L5VXB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVi7ahb06O9hcmUIp71Cyg0e9SALkMsCw',
    appId: '1:288296090804:android:2065bf3114447a99a62be1',
    messagingSenderId: '288296090804',
    projectId: 'yoo-yoo-bfe2e',
    storageBucket: 'yoo-yoo-bfe2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXhyqusIAGCZqIxpiAgdpOBMIAEC-nloQ',
    appId: '1:288296090804:ios:94be8be407358cc6a62be1',
    messagingSenderId: '288296090804',
    projectId: 'yoo-yoo-bfe2e',
    storageBucket: 'yoo-yoo-bfe2e.appspot.com',
    androidClientId: '288296090804-0c61e6uudrupu4avvasv8aie15ub0pu5.apps.googleusercontent.com',
    iosClientId: '288296090804-gidcm8fn4busr2cjuf3mggt13vgf7mn3.apps.googleusercontent.com',
    iosBundleId: 'com.yoo',
  );
}
